services:
  # 1. Backend API Service (Node.js & Express)
  backend:
    build:
      context: 058835008914.dkr.ecr.ap-south-1.amazonaws.com/backend_repo:latest
      dockerfile: Dockerfile
    container_name: url-shortener-backend
    environment:
      - PORT=5000
      - BASE_URL=http://13.232.205.135:3000
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - app-network

  # 2. Frontend Web Service (React, Vite, Nginx)
  frontend:
    build:
      context: 058835008914.dkr.ecr.ap-south-1.amazonaws.com/frontend_repo:latest
      dockerfile: Dockerfile
    container_name: url-shortener-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

# Isolated bridge network for inter-container communication
networks:
  app-network:
    driver: bridge
